object Modules {
    const val app = ":app"
    const val core = ":core"
    const val ui = ":ui"
    const val common = ":common"
    const val resources = ":resources"
    const val bottomSheet = ":bottomsheet"
    const val splash = ":features:splash"
    const val authentication = ":features:authentication"
    const val listAll = ":features:listall"
    const val search = ":features:search"
    const val watchlist = ":features:watchlist"
    const val details = ":features:details"
    const val dashboard = ":features:dashboard"
    const val settings = ":features:settings"
}
